//! Implements the generation of precomputed classification data.
//!
//! Classification data in hexbait is computed from sample files and stored in hexbait as a
//! built-in value. The sample files themselves are not committed into the hexbait repository as
//! some of them are quite large. This tool is the tool that takes a folder of sample files and
//! produces a Rust file for each sample file.

use std::{
    io::{self, Write},
    path::PathBuf,
};

use clap::Parser;
use hexbait::statistics::classification::compute_classification_data;
use hexbait_common::{Input, Len};

/// Generates hexbait classification data from a folder of samples
#[derive(Parser, Debug)]
#[command(version, about, long_about = None)]
struct Config {
    /// The folder where the samples are stored
    sample_folder: PathBuf,
    /// The folder where the output Rust files will be saved
    out_path: PathBuf,
}

/// The entry point for this application.
fn main() -> io::Result<()> {
    let config = Config::parse();

    for entry in config.sample_folder.read_dir()? {
        let entry = match entry {
            Ok(entry) => entry,
            Err(err) => {
                eprintln!("ignoring dir entry because of error: {err}");
                continue;
            }
        };

        let input = match Input::from_path(entry.path()) {
            Ok(input) => input,
            Err(err) => {
                eprintln!(
                    "ignoring file {} because of I/O error: {err}",
                    entry.path().display()
                );
                continue;
            }
        };

        if input.len() < Len::from(32 * 1024 * 1024) {
            eprintln!(
                "ignoring file {} because it is too small (min size is 32MiB)",
                entry.path().display()
            );
            continue;
        }

        let classification_data = match compute_classification_data(input) {
            Ok(classification_data) => classification_data,
            Err(err) => {
                eprintln!(
                    "ignoring file {} because of I/O error: {err}",
                    entry.path().display()
                );
                continue;
            }
        };

        let mut out_path = config.out_path.clone();
        out_path.push(entry.file_name());
        out_path.set_extension("rs");
        let name = entry.file_name();
        let name = name.to_string_lossy();

        let mut out_file = match std::fs::File::create(&out_path) {
            Ok(file) => file,
            Err(err) => {
                eprintln!("cannot write file {}: {err}", out_path.display());
                continue;
            }
        };

        let mut out_str = String::new();

        out_str.push_str(&format!(
            "//! The builtin classification data for {name}.\n"
        ));
        out_str.push_str("//!\n");
        out_str.push_str("//! This file is automatically generated by the `hexbait-generate-classification-data` tool.\n");

        out_str.push('\n');

        out_str.push_str("use super::super::ClassificationData;\n");

        out_str.push('\n');

        out_str.push_str("/// The name of the class that is classified by the classification data in this module.\n");
        out_str.push_str(&format!("pub const NAME: &str = {name:?};\n"));

        out_str.push('\n');

        out_str.push_str(&format!("/// The classification data for {name}\n"));
        out_str.push_str("#[rustfmt::skip]\n");
        out_str.push_str("#[allow(clippy::excessive_precision)]\n");
        out_str.push_str("pub static CLASSIFICATION_DATA: ClassificationData = ");
        out_str.push_str(&classification_data.as_rust_src_str());
        out_str.push_str(";\n");

        match out_file.write_all(out_str.as_bytes()) {
            Ok(_) => (),
            Err(err) => {
                eprintln!("cannot write file {}: {err}", out_path.display());
                continue;
            }
        }
    }

    Ok(())
}
