//! Contains builtin classification data.
//!
//! This data is generated by the `hexbait-generate-classification-data` tool in the same
//! repository from sample files.
//! The sample files themselves are quite large and not tracked in the repository for now.

use crate::statistics::classification::ClassificationData;

macro_rules! classification_data {
    ($classification_data:ident => $($name:ident),* $(,)?) => {
        $(
            mod $name;
        )*

        pub static $classification_data: &[(&str, &ClassificationData)] = &[
            $(
                ($name::NAME, &$name::CLASSIFICATION_DATA),
            )*
        ];
    };
}

classification_data![CLASSIFICATION_DATA =>
    amd64_code,
    base64_english_text,
    base64_high_entropy,
    english_text,
    high_entropy,
    zeroes,
];
